name: stwebclientcopyver2
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  provider: ^4.0.1

  flutter_localizations:
    sdk: flutter

  intl: ^0.16.0

  dio: ^3.0.8

  shared_preferences: ^0.5.3+5

  injector: ^1.0.8

  carousel_slider: ^1.4.1

  modal_progress_hud: ^0.1.3

  transparent_image: ^1.0.0

  flutter_html: ^0.11.1

  json_annotation: ^3.0.1

  pin_code_fields: ^2.3.0+3

  sms: ^0.2.4

  sqflite: any

  path: any

  time: ^1.2.0

  flutter_calendar_carousel: ^1.4.11

  pull_to_refresh: ^1.5.7

  url_launcher: 5.1.2

  scrolling_page_indicator: ^0.1.2

  cached_network_image: ^2.0.0

  grouped_buttons: ^1.0.4

  fluttertoast: ^3.1.3

  sliding_up_panel: ^1.0.0

  flutter_slidable: ^0.5.4

  flutter_inner_drawer: ^0.5.6+1

  get: ^2.6.3

  # google_maps_flutter: ^0.5.28+1 # app 용 (android, ios)

  flutter_google_maps: ^3.7.1 # web 용

  bootpay_api: ^1.0.9

  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.1

  build_runner: ^1.0.0

  json_serializable: ^3.2.5

flutter:

  uses-material-design: true

  assets:
    - assets/
